### ISSUE TITLE
remindme command could be run by anyone

### ISSUE THREAD

**Issue by dongle-the-gadget** [Erisa/Cliptok#108]
In `ModCmds.cs` I saw that the Remind command has `[RequireHomeServerPerm(ServerPermLevel.Tier4, WorkOutside = true)]`. The confusing thing here is that if `WorkOutside` equals `true`, the permission test would pass, making the `RequireHomeServerPerm` relatively useless.

Can you give me an explanation on how `WorkOutside` should work?

**Comment by Erisa** [comment]
The `WorkOutside` is supposed to allow the command to work outside of the home server (For example in DMs)

I've now fixed the immediate issue of it resulting in the permissions not being respected. It will still be usable by everyone in DMs for now, which I will strive to fix later.

**Comment by Erisa** [comment]
All done now, permissions will be respected correctly regardlesss of where you use the command.
![image](https://user-images.githubusercontent.com/14004943/141513791-6837aa52-1ba7-48c4-8999-d820b2db916f.png)
