### ISSUE TITLE
todo: Raidmode

### ISSUE THREAD

**Issue by Erisa** [Erisa/Cliptok#126]
Copy Vortex idea : )

**Comment by 06Sonic** [comment]
Well Vortex is open source. Maybe just cloning the code for raidmode will work?

**Comment by Erisa** [comment]
No, they're completely different programming languages and libraries that are totally incompatible with each other. All I will be copying the idea, not the code.

**Comment by Erisa** [comment]
Added in ccbf5664106844e26b8471358786937aaf283fed
