### ISSUE TITLE
Suggestion: User notes

### ISSUE THREAD

**Issue by heftymouse** [Erisa/Cliptok#135]
A system to create notes on users and recall them either on command or automatically on a certain trigger eg. an infraction being added or a modmail thread being opened.

It would consist of a /note command, with the ability to create, query and remove notes on a certain user, the bot sending a message to a channel (and mentioning the involved mod) when a user is warned, and the bot sending a message to the thread when a new modmail thread is created. This system would likely replace modmail's built-in note system to prevent fragmentation.

Config options for each note would probably include setting it to either remove itself after triggering once or be persistent, and being able to set a note to trigger either only for yourself or any mod that warns a user.

**Comment by Erisa** [comment]
So if I'm understanding this correctly, something like this?
```json
{
    "targetUserId": 486959259779596302,
    "modUserId": 228574821590499329,
    "noteText": "Keeps breaking the rules, ban them next time",
    "showOnModmail": false,
    "showOnWarn": true,
    "showAnyMod": true,
    "showOnce": false
}
```

And then `/note add` with arguments mirroing those optiions with some defaults, and something to list notes of a user (And probably one to pull a speciffic note if they end up so big we can't show them all from one command response)

It reminds me of the warnings system, just with different properties on the objects.

**Comment by heftymouse** [comment]
Yep, that looks perfect
