### ISSUE TITLE
Typo in mute message if no reason is specified

### ISSUE THREAD

**Issue by FloatingMilkshake** [Erisa/Cliptok#16]
When someone is muted, if there is no reason specified, Cliptok responds with `<user> has been muted: No reason specificed.` Notice the extra 'c' in "specificed".
![Screenshot 2021-01-22 184848](https://user-images.githubusercontent.com/51096169/105560680-80e83d00-5ce2-11eb-9ff7-4e739f76b8df.png)

**Comment by FloatingMilkshake** [comment]
Typo is also present in DM to user
![Screenshot 2021-01-22 190643](https://user-images.githubusercontent.com/51096169/105561547-fe14b180-5ce4-11eb-9842-c6cf630dcbd0.png)

**Comment by Erisa** [comment]
Despite appearing twice it seems to be set only once so it seems only one line is affected - thanks, I'll get it now
