### ISSUE TITLE
Feature Request: Use Google SafeBrowsing API.

### ISSUE THREAD

**Issue by rounk-ctrl** [Erisa/Cliptok#19]
Use Google Safe Browsing API instead of a list. It is more effective.

**Comment by torchgm** [comment]
I see no benefit in this and multiple downsides:

1. Malicious URLs aren't a huge concern for most servers.
2. Moderators wouldn't have a concrete list of what is and isn't safe at any given time without querying the Update API to download the entire list.
3. It would increase both the complexity and performance footprint, having to pull every URL from every message then wait to check it against the API.
4. We can't do anything about any mistakenly flagged URLs without even more of a performance footprint.
5. We can't unblock anything that Google flags incorrectly, we'd have to build a whitelist for the ever-changing blacklist.
6. We can't block just parts of sites or certain files which would mean that we'd be less effective at blocking certain malicious/unsavoury media.

All-in-all, the addition would potentially increase the running cost of Cliptok, lead to more false positives, increase the requirement for manual review and not serve as a replacement for the existing system anyway.

**Comment by rounk-ctrl** [comment]
well i saw a bot have it and it performs well.

**Comment by Erisa** [comment]
Personally I don't think this would be a good fit for the bot, The reasons Torch mentioned plus my own disliking for pulling in external sources to moderate the server.
If any URL are discovered to be troublesome they can be added to the list.

Thanks for the suggestion, but I won't be working on this.
