### ISSUE TITLE
Todo: Ban info command

### ISSUE THREAD

**Issue by Erisa** [Erisa/Cliptok#199]
The output of `c!debug bans <user>` but pretty with an embed

**Comment by Erisa** [comment]
Could also have mute info potentially, the embed for that one already exists for modmail

**Comment by FloatingMilkshake** [comment]
> Could also have mute info potentially

Were you thinking of having mute info shown in the same response as ban info here? You think just throwing the two embeds into the same response is okay (vs one embed with the data for both)?

Is `c!debug banstatus <user>` okay, to match `c!debug mutestatus`? Or did you want it to be a non-debug command?

**Comment by FloatingMilkshake** [comment]
> I meant separate command but combining them is honestly also fine.

I was leaning towards separate commands too tbh. So maybe like `/banstatus` and `/mutestatus`, with embeds similar to what we currently have with `c!debug mutestatus`?

**Comment by Erisa** [comment]
Sounds good
