### ISSUE TITLE
Suggestion: Context menu command to show notes

### ISSUE THREAD

**Issue by Erisa** [Erisa/Cliptok#206]
Similar to right click → "Show warnings", but for notes

**Comment by Erisa** [comment]
The same as the list should be good, though my experience with using list today made me wonder if when theres one note it could return details for just that note.

**Comment by FloatingMilkshake** [comment]
I like that idea—I can add a context menu command for list, and have that & `/note list` jump right to details if there's only a single note for a user.

**Comment by FloatingMilkshake** [comment]
Done in 5ac634d!
