### ISSUE TITLE
Temporary warnings

### ISSUE THREAD

**Issue by itsWindows11** [Erisa/Cliptok#211]
Cliptok should have an option to warn people with a temporary duration, so the warn expires after a specific period. The warning gets removed after it gets expired.

By default, a warn should expire after a week or 4 days, and increases when the member has more warnings if the duration isn't specified manually. This can be left up for discussion, but ideally should be after a member is expected to behave.

Something like:
```
/warn [member] expires: [period (or any other string that isn't a valid period for making the warning permanent)]
```

This can ensure more fair-ness for moderation actions.

**Comment by Erisa** [comment]
This would be a fundamental moderation policy change and should be raised in a modmail for wider discussion with the mod team, rather than being raised as a bot issue.
