### ISSUE TITLE
Suggestion: !report feature

### ISSUE THREAD

**Issue by bulgit** [Erisa/Cliptok#52]
A feature that would let users easily report a message without going into Mod mail! I think an automated report system is a really cool feature for faster moderation and faster report.
To be honest I may be one of the people who is not really comfortable with _Moderate the mail_, because it requires transitioning from group to individual.

**How would it works?**
People would be able to report a message through a command (which would require the message ID, or the message link whatever is preferable) and specify a reason or rule number. Moderators will have to read and process the report, users notified about the report status. Only a single report is created for each message: if someone attempts to report a message that was already reported, the report will just be pushed instead.

**Command**
The command would look like this:
`!report msg_id [reason]` or `!report msg_id [rule(s) ...]`

example:
`!report 123456789012345678 insult` or `!report 123456789012345678 1 16`

**Moderation command**
There would be another command for moderators if the given reason/rules don't match the actual infraction:
`!report_fix msg_id [new_reason]` or `!report_fix msg_id [new_rules]`

example:
`!report_fix 123456789012345678 drama` or `!report_fix 123456789012345678 4 16`

**Report**
Once a message is reported, users could then receive a DM from the bot telling the report was sent:
![image](https://user-images.githubusercontent.com/86486567/124007684-e05a1f80-d9db-11eb-9b1f-a202a6f0a27a.png)

The report is then transmitted into the moderation channel, and could look like this:
![image](https://user-images.githubusercontent.com/86486567/124007747-f23bc280-d9db-11eb-8a9f-463c492a2365.png)

- Green circle: validate and warn the reported user. Maybe delete the reported message as well?
- Red circle: reject the report

Multiple users could report the same message if it was not processed, the bot will just edit the message to add another embed of the user who reported the message. I suggest adding the list of those who reported like above, so you can take appropriate actions in case of abuse.

Whenever a moderator processes the report, users who reported will be notified, indicating whether or not the message is against the server rules.

**Conditions**

Attempting to report a message that was previously moderated (previous report was processed), could result in this message being received in DM instead:
![image](https://user-images.githubusercontent.com/86486567/124005914-ed760f00-d9d9-11eb-8932-717a3bd90921.png)

If a moderator validates the report, the DM notification could look like:
![image](https://user-images.githubusercontent.com/86486567/124007845-0f709100-d9dc-11eb-85b7-573b969553b2.png)
If a moderator rejects the report, the DM notification could look like:
![image](https://user-images.githubusercontent.com/86486567/124007818-08e21980-d9dc-11eb-8c19-a3d69539f87f.png)

Messages sent by the bot could be of course better!

**Comment by Erisa** [comment]
This is not something we are interested in adding, so I will be closing the issue for now.
You are more than welcome to have it in your server or bot/fork, but we are not supporting it on Cliptok as part of Microsoft Community.
