### ISSUE TITLE
Todo: /role command

### ISSUE THREAD

**Issue by Erisa** [Erisa/Cliptok#95]

**Comment by itsWindows11** [comment]
What should this command do exactly?

**Comment by Erisa** [comment]
Main thing was replace all of these
<img width="474" alt="image" src="https://user-images.githubusercontent.com/14004943/200602851-961f91b9-d020-4a3c-b0ae-73aec1eadb40.png">

Probably in a similar way to what the Cloudflare Developers Discord has:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/14004943/200603065-905941e5-b08b-4ec2-b3f6-f22ec0087ef2.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/14004943/200603103-374f354f-157e-4165-aa60-e46136e4db5a.png">

**Comment by itsWindows11** [comment]
Oh I see, will get to working on it soon.

**Comment by itsWindows11** [comment]
Btw last question, should I use the announcement roles or make a new "grantable roles" field incase there can be any role that isn't related to announcements but can be self-granted?

**Comment by Erisa** [comment]
> make a new "grantable roles" field incase there can be any role that isn't related to announcements but can be self-granted?
This seems like it would make the most sense - there can be a config mapping of role names and IDs to populate the list with

**Comment by itsWindows11** [comment]
I'll see, I have implemented something at least but can't test it because for some reason the new command doesn't get registered on my own testing bot.

**Comment by Erisa** [comment]
D#+ doesn't expose registration errors very well, if a command isn't registering then try checking that all descriptions are within the character limit and that there are no capital letters in command and option names. Could be a number of things but that's the most common I run into
